grafana:
  enabled: true
  service:
    port: 80
    type: LoadBalancer

prometheus:
  enabled: true
  service:
    port: 80
    type: LoadBalancer

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
